/**
 * Notion Schema Generator: UPG → Notion (write direction)
 *
 * Given a UPG graph (nodes + edges), emits the full set of Notion API
 * payloads needed to create a correctly structured, edge-linked workspace:
 *
 *   1. One Notion database per UPG entity type present in the graph
 *   2. Relation properties wired between databases to represent UPG edges
 *   3. One Notion page per UPG node, with properties mapped from the node
 *   4. Relation links populated once page IDs are known
 *
 * This is the primary integration direction for the Notion adapter.
 * No HTTP calls are made here: this module produces a NotionWorkspacePlan
 * that the caller executes against the Notion API.
 *
 * Algorithm (from notion-mapping.md §6):
 *   1. Read the UPG graph (entity types + edge types present)
 *   2. For each entity type → create a Notion database with canonical properties
 *   3. For each edge type → create a relation property on the source database
 *   4. For each node → create a Notion page in the corresponding database
 *   5. Return the full workspace plan
 */

import type { UPGBaseNode, UPGEdge } from '@unified-product-graph/core'
import type {
  NotionDatabasePlan,
  NotionDatabaseSchema,
  NotionPagePlan,
  NotionPageProperties,
  NotionRelationLink,
  NotionRelationProperty,
  NotionWorkspacePlan,
} from './notion-types.js'

// ─── Entity type → human-readable database name ───────────────────────────────

/**
 * Maps UPG entity types to their canonical Notion database names.
 * These are the names Notion users will see in their workspace.
 */
export const ENTITY_DATABASE_NAMES: Record<string, string> = {
  opportunity: 'Opportunities',
  solution: 'Solutions',
  outcome: 'Outcomes',
  feature: 'Features',
  feature_area: 'Feature Areas',
  epic: 'Epics',
  user_story: 'Stories',
  task: 'Tasks',
  bug: 'Bugs',
  insight: 'Insights',
  observation: 'Observations',
  persona: 'Personas',
  hypothesis: 'Hypotheses',
  experiment: 'Experiments',
  decision: 'Decisions',
  assumption: 'Assumptions',
  metric: 'Metrics',
  objective: 'Objectives',
  key_result: 'Key Results',
  initiative: 'Initiatives',
  project: 'Projects',
  milestone: 'Milestones',
  release: 'Releases',
  research_study: 'Research Studies',
  participant: 'Participants',
  competitor: 'Competitors',
  competitor_feature: 'Competitor Features',
  content_calendar: 'Content Calendar',
  content_piece: 'Content',
  document: 'Documents',
  knowledge_base_article: 'Knowledge Base',
  team: 'Teams',
  role: 'Roles',
  roadmap_item: 'Roadmap',
  changelog: 'Changelog',
  learning: 'Learnings',
  evidence: 'Evidence',
  risk: 'Risks',
  dependency: 'Dependencies',
  stakeholder: 'Stakeholders',
}

/** Get the Notion database name for a UPG entity type */
export function getDatabaseName(entityType: string): string {
  return ENTITY_DATABASE_NAMES[entityType] ?? toTitleCase(entityType.replace(/_/g, ' '))
}

// ─── Edge type → relation property forward verb ───────────────────────────────

/**
 * Maps UPG edge types to the forward verb used as the Notion relation property name.
 * The reverse relation name is auto-generated by Notion and stored in `reverse_name`.
 *
 * All edge types verified against the live catalog via list_edge_types.
 */
export const EDGE_RELATION_VERBS: Record<string, { forward: string; reverse: string }> = {
  insight_informs_opportunity: { forward: 'Informs', reverse: 'Informed by' },
  insight_informs_job: { forward: 'Informs Job', reverse: 'Insights' },
  insight_informs_solution: { forward: 'Informs Solution', reverse: 'Insights' },
  opportunity_drives_solution: { forward: 'Drives', reverse: 'Addresses' },
  solution_proposes_hypothesis: { forward: 'Proposes Hypothesis', reverse: 'Proposed by' },
  research_study_produces_insight: { forward: 'Produces', reverse: 'Source Study' },
  research_study_enrolls_participant: { forward: 'Participants', reverse: 'Studies' },
  observation_yields_insight: { forward: 'Yields', reverse: 'From Observation' },
  outcome_delivered_by_feature: { forward: 'Delivered by', reverse: 'Delivers' },
  outcome_delivered_via_feature_area: { forward: 'Delivered via Area', reverse: 'Delivers Outcome' },
  initiative_drives_outcome: { forward: 'Drives', reverse: 'Driven by Initiative' },
  feature_decomposed_into_epic: { forward: 'Epics', reverse: 'Feature' },
  epic_specified_by_user_story: { forward: 'Stories', reverse: 'Epic' },
  project_implements_initiative: { forward: 'Implements', reverse: 'Implemented by' },
  document_describes_decision: { forward: 'Describes Decision', reverse: 'Documented in' },
  document_contains_insight: { forward: 'Contains Insight', reverse: 'Source Document' },
  content_calendar_schedules_content_piece: { forward: 'Schedules', reverse: 'Scheduled in' },
  content_calendar_schedules_knowledge_base_article: { forward: 'Schedules Article', reverse: 'Scheduled in' },
  node_owned_by_team: { forward: 'Owned by', reverse: 'Owns' },
  node_owned_by_role: { forward: 'Owner Role', reverse: 'Owns' },
}

// ─── Entity-specific property schemas ────────────────────────────────────────

/**
 * Returns the Notion database property schema for a given UPG entity type.
 *
 * Every schema includes:
 * - Name (title: required by Notion)
 * - Description (rich_text)
 * - Status (status: maps to UPG lifecycle)
 * - UPG ID (unique_id: the sync anchor storing the UPG node_id)
 *
 * Entity-specific properties are added on top.
 */
export function generateDatabaseSchema(entityType: string): NotionDatabaseSchema {
  const base: NotionDatabaseSchema = {
    Name: {
      type: 'title',
      name: 'Name',
      required: true,
      description: 'The name or title of this entity',
    },
    Description: {
      type: 'rich_text',
      name: 'Description',
      description: 'A detailed description of this entity',
    },
    Status: {
      type: 'status',
      name: 'Status',
      groups: [
        {
          name: 'Not started',
          color: 'default',
          options: [
            { name: 'Planned', color: 'default' },
            { name: 'Backlog', color: 'gray' },
          ],
        },
        {
          name: 'In progress',
          color: 'blue',
          options: [
            { name: 'In Progress', color: 'blue' },
            { name: 'In Review', color: 'purple' },
            { name: 'Blocked', color: 'red' },
          ],
        },
        {
          name: 'Done',
          color: 'green',
          options: [
            { name: 'Done', color: 'green' },
            { name: 'Archived', color: 'gray' },
          ],
        },
      ],
    },
    'UPG ID': {
      type: 'unique_id',
      name: 'UPG ID',
      description: 'The UPG node ID. Sync anchor for bidirectional UPG ↔ Notion sync.',
    },
  }

  // Entity-specific extensions
  const extensions: Record<string, NotionDatabaseSchema> = {
    opportunity: {
      Severity: {
        type: 'select',
        name: 'Severity',
        options: [
          { name: 'Critical', color: 'red' },
          { name: 'High', color: 'orange' },
          { name: 'Medium', color: 'yellow' },
          { name: 'Low', color: 'gray' },
        ],
        description: 'How severely this opportunity impacts users',
      },
      Frequency: {
        type: 'select',
        name: 'Frequency',
        options: [
          { name: 'Always', color: 'red' },
          { name: 'Often', color: 'orange' },
          { name: 'Sometimes', color: 'yellow' },
          { name: 'Rarely', color: 'gray' },
        ],
        description: 'How often users encounter this problem',
      },
      Owner: {
        type: 'people',
        name: 'Owner',
        description: 'The person responsible for this opportunity',
      },
    },

    solution: {
      Approach: {
        type: 'select',
        name: 'Approach',
        options: [
          { name: 'Build', color: 'blue' },
          { name: 'Buy', color: 'green' },
          { name: 'Partner', color: 'purple' },
          { name: 'Defer', color: 'gray' },
        ],
      },
      Owner: {
        type: 'people',
        name: 'Owner',
        description: 'The person driving this solution',
      },
    },

    outcome: {
      'Target Value': {
        type: 'number',
        name: 'Target Value',
        number_format: 'number',
        description: 'The target metric value for this outcome',
      },
      'Current Value': {
        type: 'number',
        name: 'Current Value',
        number_format: 'number',
        description: 'The current metric value',
      },
      'Time Horizon': {
        type: 'select',
        name: 'Time Horizon',
        options: [
          { name: 'Q1', color: 'blue' },
          { name: 'Q2', color: 'green' },
          { name: 'Q3', color: 'yellow' },
          { name: 'Q4', color: 'orange' },
        ],
      },
    },

    feature: {
      Priority: {
        type: 'select',
        name: 'Priority',
        options: [
          { name: 'P0 Critical', color: 'red' },
          { name: 'P1 High', color: 'orange' },
          { name: 'P2 Medium', color: 'yellow' },
          { name: 'P3 Low', color: 'gray' },
        ],
      },
      'Target Release': {
        type: 'select',
        name: 'Target Release',
        description: 'Which release this feature is targeted for',
      },
      Owner: {
        type: 'people',
        name: 'Owner',
      },
    },

    epic: {
      Priority: {
        type: 'select',
        name: 'Priority',
        options: [
          { name: 'P0', color: 'red' },
          { name: 'P1', color: 'orange' },
          { name: 'P2', color: 'yellow' },
          { name: 'P3', color: 'gray' },
        ],
      },
      Assignee: {
        type: 'people',
        name: 'Assignee',
      },
      'Due Date': {
        type: 'date',
        name: 'Due Date',
      },
    },

    user_story: {
      'Acceptance Criteria': {
        type: 'rich_text',
        name: 'Acceptance Criteria',
        description: 'Definition of done for this story',
      },
      Points: {
        type: 'number',
        name: 'Points',
        number_format: 'number',
        description: 'Story points estimate',
      },
      Assignee: {
        type: 'people',
        name: 'Assignee',
      },
    },

    task: {
      Assignee: {
        type: 'people',
        name: 'Assignee',
      },
      'Due Date': {
        type: 'date',
        name: 'Due Date',
      },
      Priority: {
        type: 'select',
        name: 'Priority',
        options: [
          { name: 'Urgent', color: 'red' },
          { name: 'High', color: 'orange' },
          { name: 'Medium', color: 'yellow' },
          { name: 'Low', color: 'gray' },
        ],
      },
    },

    bug: {
      Severity: {
        type: 'select',
        name: 'Severity',
        options: [
          { name: 'Critical', color: 'red' },
          { name: 'High', color: 'orange' },
          { name: 'Medium', color: 'yellow' },
          { name: 'Low', color: 'gray' },
        ],
      },
      Reporter: {
        type: 'people',
        name: 'Reporter',
      },
      Assignee: {
        type: 'people',
        name: 'Assignee',
      },
      'Steps to Reproduce': {
        type: 'rich_text',
        name: 'Steps to Reproduce',
      },
    },

    insight: {
      Source: {
        type: 'select',
        name: 'Source',
        options: [
          { name: 'User Interview', color: 'blue' },
          { name: 'Survey', color: 'green' },
          { name: 'Support Ticket', color: 'orange' },
          { name: 'Analytics', color: 'purple' },
          { name: 'Sales Call', color: 'yellow' },
          { name: 'Other', color: 'gray' },
        ],
      },
      Category: {
        type: 'select',
        name: 'Category',
        options: [
          { name: 'Pain Point', color: 'red' },
          { name: 'Desire', color: 'green' },
          { name: 'Behaviour', color: 'blue' },
          { name: 'Context', color: 'gray' },
        ],
      },
    },

    persona: {
      'Job Title': {
        type: 'rich_text',
        name: 'Job Title',
      },
      Goals: {
        type: 'rich_text',
        name: 'Goals',
        description: 'What this persona is trying to achieve',
      },
      Frustrations: {
        type: 'rich_text',
        name: 'Frustrations',
        description: 'What gets in the way',
      },
      'Primary Job': {
        type: 'rich_text',
        name: 'Primary Job',
        description: 'The main job-to-be-done for this persona',
      },
    },

    hypothesis: {
      'Confidence Level': {
        type: 'select',
        name: 'Confidence Level',
        options: [
          { name: 'High', color: 'green' },
          { name: 'Medium', color: 'yellow' },
          { name: 'Low', color: 'red' },
          { name: 'Unknown', color: 'gray' },
        ],
      },
      'Validation Method': {
        type: 'select',
        name: 'Validation Method',
        options: [
          { name: 'A/B Test', color: 'blue' },
          { name: 'User Interview', color: 'purple' },
          { name: 'Survey', color: 'green' },
          { name: 'Prototype Test', color: 'orange' },
          { name: 'Analytics', color: 'yellow' },
        ],
      },
    },

    experiment: {
      Method: {
        type: 'select',
        name: 'Method',
        options: [
          { name: 'A/B Test', color: 'blue' },
          { name: 'Usability Test', color: 'purple' },
          { name: 'Prototype', color: 'orange' },
          { name: 'Survey', color: 'green' },
          { name: 'Interview', color: 'yellow' },
        ],
      },
      Result: {
        type: 'select',
        name: 'Result',
        options: [
          { name: 'Validated', color: 'green' },
          { name: 'Invalidated', color: 'red' },
          { name: 'Inconclusive', color: 'yellow' },
          { name: 'Pending', color: 'gray' },
        ],
      },
      'Start Date': {
        type: 'date',
        name: 'Start Date',
      },
      'End Date': {
        type: 'date',
        name: 'End Date',
      },
    },

    decision: {
      'Decision Date': {
        type: 'date',
        name: 'Decision Date',
      },
      Rationale: {
        type: 'rich_text',
        name: 'Rationale',
        description: 'Why this decision was made',
      },
      'Alternatives Considered': {
        type: 'rich_text',
        name: 'Alternatives Considered',
      },
      'Decision Maker': {
        type: 'people',
        name: 'Decision Maker',
      },
    },

    assumption: {
      'Risk Level': {
        type: 'select',
        name: 'Risk Level',
        options: [
          { name: 'High', color: 'red' },
          { name: 'Medium', color: 'yellow' },
          { name: 'Low', color: 'green' },
        ],
      },
      'Validation Status': {
        type: 'select',
        name: 'Validation Status',
        options: [
          { name: 'Unvalidated', color: 'gray' },
          { name: 'Testing', color: 'blue' },
          { name: 'Validated', color: 'green' },
          { name: 'Invalidated', color: 'red' },
        ],
      },
    },

    metric: {
      'Current Value': {
        type: 'number',
        name: 'Current Value',
        number_format: 'number',
      },
      'Target Value': {
        type: 'number',
        name: 'Target Value',
        number_format: 'number',
      },
      Unit: {
        type: 'select',
        name: 'Unit',
        options: [
          { name: '%', color: 'blue' },
          { name: 'Count', color: 'green' },
          { name: '$', color: 'yellow' },
          { name: 'Days', color: 'gray' },
          { name: 'Score', color: 'purple' },
        ],
      },
      Direction: {
        type: 'select',
        name: 'Direction',
        options: [
          { name: 'Increase', color: 'green' },
          { name: 'Decrease', color: 'red' },
          { name: 'Maintain', color: 'gray' },
        ],
      },
      Owner: {
        type: 'people',
        name: 'Owner',
      },
    },

    objective: {
      Quarter: {
        type: 'select',
        name: 'Quarter',
        options: [
          { name: 'Q1', color: 'blue' },
          { name: 'Q2', color: 'green' },
          { name: 'Q3', color: 'yellow' },
          { name: 'Q4', color: 'orange' },
        ],
      },
      Owner: {
        type: 'people',
        name: 'Owner',
      },
    },

    key_result: {
      'Start Value': {
        type: 'number',
        name: 'Start Value',
        number_format: 'number',
      },
      'Target Value': {
        type: 'number',
        name: 'Target Value',
        number_format: 'number',
      },
      'Current Value': {
        type: 'number',
        name: 'Current Value',
        number_format: 'number',
      },
      Quarter: {
        type: 'select',
        name: 'Quarter',
        options: [
          { name: 'Q1', color: 'blue' },
          { name: 'Q2', color: 'green' },
          { name: 'Q3', color: 'yellow' },
          { name: 'Q4', color: 'orange' },
        ],
      },
      Owner: {
        type: 'people',
        name: 'Owner',
      },
    },

    initiative: {
      'Start Date': {
        type: 'date',
        name: 'Start Date',
      },
      'End Date': {
        type: 'date',
        name: 'End Date',
      },
      Owner: {
        type: 'people',
        name: 'Owner',
      },
    },

    project: {
      'Start Date': {
        type: 'date',
        name: 'Start Date',
      },
      'End Date': {
        type: 'date',
        name: 'End Date',
      },
      Owner: {
        type: 'people',
        name: 'Owner',
      },
    },

    release: {
      'Release Date': {
        type: 'date',
        name: 'Release Date',
      },
      Version: {
        type: 'rich_text',
        name: 'Version',
        description: 'Semantic version string (e.g. 1.4.0)',
      },
    },

    research_study: {
      Method: {
        type: 'select',
        name: 'Method',
        options: [
          { name: 'User Interview', color: 'blue' },
          { name: 'Usability Test', color: 'purple' },
          { name: 'Survey', color: 'green' },
          { name: 'Contextual Inquiry', color: 'orange' },
          { name: 'Diary Study', color: 'yellow' },
        ],
      },
      'Study Date': {
        type: 'date',
        name: 'Study Date',
      },
      'Participant Count': {
        type: 'number',
        name: 'Participant Count',
        number_format: 'number',
      },
      Researcher: {
        type: 'people',
        name: 'Researcher',
      },
    },

    competitor: {
      URL: {
        type: 'url',
        name: 'URL',
        description: 'Competitor website',
      },
      Strengths: {
        type: 'rich_text',
        name: 'Strengths',
      },
      Weaknesses: {
        type: 'rich_text',
        name: 'Weaknesses',
      },
      'Pricing Model': {
        type: 'select',
        name: 'Pricing Model',
        options: [
          { name: 'Freemium', color: 'blue' },
          { name: 'Subscription', color: 'green' },
          { name: 'Per-seat', color: 'purple' },
          { name: 'Usage-based', color: 'orange' },
          { name: 'Enterprise', color: 'red' },
        ],
      },
    },
  }

  const entityExtensions = extensions[entityType] ?? {}
  return { ...base, ...entityExtensions }
}

// ─── Edge → relation property ─────────────────────────────────────────────────

/**
 * Given a UPG edge type and the target database name, returns the Notion
 * relation property spec to add to the source database.
 */
export function generateRelationProperty(
  edgeType: string,
  targetDatabaseName: string,
): NotionRelationProperty {
  const verbs = EDGE_RELATION_VERBS[edgeType]
  const forwardVerb = verbs?.forward ?? toTitleCase(edgeType.replace(/_/g, ' '))
  const reverseVerb = verbs?.reverse ?? `← ${targetDatabaseName}`

  return {
    name: forwardVerb,
    target_database_name: targetDatabaseName,
    two_way: true,
    reverse_name: reverseVerb,
    upg_edge_type: edgeType,
  }
}

// ─── Node → page properties ───────────────────────────────────────────────────

/**
 * Maps a UPG node's fields to Notion page property values.
 */
function mapNodeToPageProperties(node: UPGBaseNode): NotionPageProperties {
  const props: NotionPageProperties = {
    Name: { type: 'title', value: node.title },
    'UPG ID': { type: 'unique_id', value: node.id },
  }

  if (node.description) {
    props['Description'] = { type: 'rich_text', value: node.description }
  }

  if (node.status) {
    props['Status'] = { type: 'status', value: node.status }
  }

  return props
}

// ─── Workspace plan generator ─────────────────────────────────────────────────

/**
 * Given a complete UPG graph (nodes + edges), returns the full set of Notion
 * API calls needed to create the workspace.
 *
 * Execution order for the caller:
 *   1. Create all databases (from `databases`)
 *   2. Create all pages once database IDs are known (from `pages`)
 *   3. Populate relation properties once page IDs are known (from `relations`)
 */
export function generateNotionWorkspace(
  nodes: UPGBaseNode[],
  edges: UPGEdge[],
): NotionWorkspacePlan {
  const warnings: string[] = []
  const databasePlans = new Map<string, NotionDatabasePlan>()

  // ── 1. Collect entity types from nodes ───────────────────────────────────
  const entityTypes = new Set<string>()
  for (const node of nodes) {
    entityTypes.add(node.type as string)
  }

  // ── 2. Create one database plan per entity type ──────────────────────────
  for (const entityType of entityTypes) {
    const databaseName = getDatabaseName(entityType)
    databasePlans.set(entityType, {
      entity_type: entityType,
      database_name: databaseName,
      properties: generateDatabaseSchema(entityType),
      relations: [],
    })
  }

  // ── 3. Process edges → add relation properties to source databases ────────
  const processedEdgeTypes = new Set<string>()

  for (const edge of edges) {
    const sourceNode = nodes.find((n) => n.id === edge.source)
    const targetNode = nodes.find((n) => n.id === edge.target)

    if (!sourceNode || !targetNode) {
      warnings.push(
        `Edge "${edge.type}" references unknown node. Skipped. ` +
          `(source: ${edge.source}, target: ${edge.target})`,
      )
      continue
    }

    const sourceType = sourceNode.type as string
    const targetType = targetNode.type as string
    const edgeKey = `${edge.type}::${sourceType}::${targetType}`

    // Deduplicate: only add the relation property once per edge type + type pair
    if (processedEdgeTypes.has(edgeKey)) continue
    processedEdgeTypes.add(edgeKey)

    const sourcePlan = databasePlans.get(sourceType)
    if (!sourcePlan) continue

    const targetDatabaseName = getDatabaseName(targetType)
    const relationProp = generateRelationProperty(edge.type, targetDatabaseName)

    // Avoid duplicate relation properties on the same database
    const alreadyAdded = sourcePlan.relations.some(
      (r) => r.upg_edge_type === edge.type && r.target_database_name === targetDatabaseName,
    )
    if (!alreadyAdded) {
      sourcePlan.relations.push(relationProp)
    }
  }

  // ── 4. Build page plans (one per UPG node) ────────────────────────────────
  const pages: NotionPagePlan[] = nodes.map((node) => ({
    entity_type: node.type as string,
    database_name: getDatabaseName(node.type as string),
    properties: mapNodeToPageProperties(node),
    source_node_id: node.id,
  }))

  // ── 5. Build relation links (populated after pages are created) ───────────
  // Source/target page IDs are not yet known: they will be filled in by the
  // caller once Notion page creation responses are received. We emit the
  // structural plan so the caller knows which pages to link.
  const relations: NotionRelationLink[] = edges
    .filter((edge) => {
      const src = nodes.find((n) => n.id === edge.source)
      const tgt = nodes.find((n) => n.id === edge.target)
      if (!src || !tgt) return false
      if (!EDGE_RELATION_VERBS[edge.type]) {
        warnings.push(
          `Edge type "${edge.type}" has no Notion relation verb mapping. ` +
            `The edge will not appear as a Notion relation property. ` +
            `Add it to EDGE_RELATION_VERBS to enable this.`,
        )
        return false
      }
      return true
    })
    .map((edge) => {
      const verbs = EDGE_RELATION_VERBS[edge.type]
      return {
        source_page_id: edge.source, // placeholder: caller replaces with Notion page ID
        relation_property: verbs.forward,
        target_page_id: edge.target, // placeholder: caller replaces with Notion page ID
        edge_type: edge.type,
      }
    })

  // ── 6. Warn on entity types with no database schema ──────────────────────
  for (const entityType of entityTypes) {
    if (!ENTITY_DATABASE_NAMES[entityType]) {
      warnings.push(
        `Entity type "${entityType}" has no canonical Notion database name. ` +
          `A database name was auto-generated. Add it to ENTITY_DATABASE_NAMES for a stable name.`,
      )
    }
  }

  return {
    databases: Array.from(databasePlans.values()),
    pages,
    relations,
    warnings,
  }
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function toTitleCase(str: string): string {
  return str.replace(/\b\w/g, (c) => c.toUpperCase())
}
